### ISSUE TITLE
No module named 'dotmap'

### ISSUE THREAD

**Issue by emjay73** [skyhehe123/AutoRF-pytorch#6]
Hi, I tried to execute the file preproc.py, but failed with the following error.

```
python scripts/preproc.py                                                                                                      
Traceback (most recent call last):                                                                     
  File "scripts/preproc.py", line 21, in <module>                                                 
import kitti_util                                                                                  
  File "src/kitti_util.py", line 1, in <module>     
from dotmap import DotMap                                                                          
ModuleNotFoundError: No module named 'dotmap'                                        
```
Where can I find dotmap related files?
Thank you in advance and thank you for sharing the code.

**Comment by emjay73** [comment]
I just realized that the code works independently of the Dotmap.
I commented the line 'from dotmap import DotMap' to solve the issue.
